# MPHC (MultiplayerHardcore) config.

# Time of play
timeOfPlay:
  MONDAY: "open"
  TUESDAY: "open"
  WEDNESDAY: "open"
  THURSDAY: "open"
  FRIDAY: "open"
  SATURDAY: "open"
  SUNDAY: "open"

# For posting player death notices to Discord using a webhook
discord:
  enabled: false
  webhookUrl: null

motd:
  enabled: false
  line1: "Multiplayer Hardcore!"
  line2default: "Attempt #%d"
  line2closed: "Next playtime: %s"
  line2busy: "(Busy, try again soon!)"
  line2broken: "Broken :("

# Fancy death messages
messages:
  # Will be appended to every other message.
  ending: "Your journey begins anew..."
  # Messages for specific death causes
  DRAGON_BREATH:
    - "%1$s burned up while making a valiant stand against %2$s."
  DROWNING:
    - "%1$s drowned."
  ENTITY_ATTACK:
    - "%1$s was butchered by %2$s."
  ENTITY_EXPLOSION:
    - "%2$s blew itself up, taking %1$s with it."
  FALL:
    - "%1$s falls to doom!"
  FALLING_BLOCK:
    - "%1$s was crushed by a falling %2$s."
  LIGHTNING:
    - "And it came to pass that %1$s was struck by lightning!"
  MAGIC:
    - "%1$s was snuffed out by %1$s's evil spell."
  PROJECTILE:
    - "%1$s was shot to death by %2$s."
  # Messages for when there are no specific messages for the death cause in question.
  generic:
    - "%1$s walked into the light."
    - "%1$s died."

attempt:
  worldPrefix: "attempt"
  attemptsToKeep: 10
  # The current attempt number. DO NOT EDIT!
  current: 1
